name:       cs340mp

# By signing below, I pledge on my honor that I neither gave nor received any
# unauthorized assistance on the code contained in this repository. I understand
# that cheating/plagiarism will result in, at minimum, a score of zero on the
# assignment, and possible removal from the class with a failing grade.

author:     "Yahya alqahtani"      # your name
maintainer: "yalqahtani3@hawk.iit.edu"  # your IIT email

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5
- random
- hspec
- HUnit
- QuickCheck

executables:
  mp:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cs340mp
    when:
    - condition: false
      other-modules: Paths_cs340mp

library:
  source-dirs: src
  when:
  - condition: false
    other-modules: Paths_cs340mp

tests:
  mp-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cs340mp
